name: 'Continuous Integration'
on:
  - workflow_dispatch
  - push
jobs:
  continuous-integration:
    uses: melusina-org/reusable/.github/workflows/lisp-continuous-integration.yaml@support-parameters
